runtime: python39
entrypoint: gunicorn -b :$PORT app:app
instance_class: F4_1G
automatic_scaling:
  target_cpu_utilization: 0.8
  min_idle_instances: 1
  max_idle_instances: 5
  min_pending_latency: 100ms
  max_pending_latency: 300ms
