runtime: python39
env: standard
instance_class: F2
handlers:
  - url: .*
    script: auto
automatic_scaling:
  target_cpu_utilization: 0.8
  min_idle_instances: 1
  max_idle_instances: 5
  min_pending_latency: 100ms
  max_pending_latency: 300ms
service_account: social-lips-398506@appspot.gserviceaccount.com
